In [74]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

In [75]:
# fetch dataset 
car_evaluation = fetch_ucirepo(id=19) 
  
# data (as pandas dataframes) 
x = car_evaluation.data.features 
y = car_evaluation.data.targets

In [76]:
# variable information 
car_evaluation.variables

,name,role,type,demographic,description,units,missing_values
0,buying,Feature,Categorical,None,buying price,None,no
1,maint,Feature,Categorical,None,price of the maintenance,None,no
2,doors,Feature,Categorical,None,number of doors,None,no
3,persons,Feature,Categorical,None,capacity in terms of persons to carry,None,no
4,lug_boot,Feature,Categorical,None,the size of luggage boot,None,no
5,safety,Feature,Categorical,None,estimated safety of the car,None,no
6,class,Target,Categorical,None,"evaulation level (unacceptable, acceptable, go...",None,no

In [ ]:
x.head()

(  buying  maint doors persons lug_boot safety
 0  vhigh  vhigh     2       2    small    low
 1  vhigh  vhigh     2       2    small    med
 2  vhigh  vhigh     2       2    small   high
 3  vhigh  vhigh     2       2      med    low
 4  vhigh  vhigh     2       2      med    med,
    class
 0  unacc
 1  unacc
 2  unacc
 3  unacc
 4  unacc)

In [85]:
y.head()

   class
0  unacc
1  unacc
2  unacc
3  unacc
4  unacc

In [65]:
for i in x:
    print(i,":=",list(x[i].unique()))

print("class :=",list(y['class'].unique()))

buying := ['vhigh', 'high', 'med', 'low']
maint := ['vhigh', 'high', 'med', 'low']
doors := ['2', '3', '4', '5more']
persons := ['2', '4', 'more']
lug_boot := ['small', 'med', 'big']
safety := ['low', 'med', 'high']
class := ['unacc', 'acc', 'vgood', 'good']

In [123]:
# preprocessing of data
# converting data into transaction format

dataset=x
dataset['class']=y['class']
encoded_dataset = pd.get_dummies(dataset)
encoded_dataset

,buying_high,buying_low,buying_med,buying_vhigh,maint_high,maint_low,maint_med,maint_vhigh,doors_2,doors_3,...,lug_boot_big,lug_boot_med,lug_boot_small,safety_high,safety_low,safety_med,class_acc,class_good,class_unacc,class_vgood
0,False,False,False,True,False,False,False,True,True,False,...,False,False,True,False,True,False,False,False,True,False
1,False,False,False,True,False,False,False,True,True,False,...,False,False,True,False,False,True,False,False,True,False
2,False,False,False,True,False,False,False,True,True,False,...,False,False,True,True,False,False,False,False,True,False
3,False,False,False,True,False,False,False,True,True,False,...,False,True,False,False,True,False,False,False,True,False
4,False,False,False,True,False,False,False,True,True,False,...,False,True,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,False,True,False,False,False,True,False,False,False,False,...,False,True,False,False,False,True,False,True,False,False
1724,False,True,False,False,False,True,False,False,False,False,...,False,True,False,True,False,False,False,False,False,True
1725,False,True,False,False,False,True,False,False,False,False,...,True,False,False,False,True,False,False,False,True,False
1726,False,True,False,False,False,True,False,False,False,False,...,True,False,False,False,False,True,False,True,False,False
1727,False,True,False,False,False,True,False,False,False,False,...,True,False,False,True,False,False,False,False,False,True

In [124]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(encoded_dataset, min_support=0.1, use_colnames=True)

In [125]:
frequent_itemsets

     support                                           itemsets
0   0.250000                           frozenset({buying_high})
1   0.250000                            frozenset({buying_low})
2   0.250000                            frozenset({buying_med})
3   0.250000                          frozenset({buying_vhigh})
4   0.250000                            frozenset({maint_high})
..       ...                                                ...
81  0.111111    frozenset({safety_low, persons_4, class_unacc})
82  0.111111  frozenset({safety_low, persons_more, class_una...
83  0.111111  frozenset({lug_boot_big, safety_low, class_una...
84  0.111111  frozenset({safety_low, lug_boot_med, class_una...
85  0.111111  frozenset({lug_boot_small, safety_low, class_u...

[86 rows x 2 columns]

In [126]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

In [127]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({buying_high}),frozenset({class_unacc}),0.250000,0.700231,0.187500,0.750000,1.071074,1.0,0.012442,1.199074,0.088477,0.245827,0.166023,0.508884
1,frozenset({buying_vhigh}),frozenset({class_unacc}),0.250000,0.700231,0.208333,0.833333,1.190083,1.0,0.033275,1.798611,0.212963,0.280811,0.444015,0.565427
2,frozenset({maint_high}),frozenset({class_unacc}),0.250000,0.700231,0.181713,0.726852,1.038017,1.0,0.006655,1.097458,0.048832,0.236446,0.088803,0.493178
3,frozenset({maint_vhigh}),frozenset({class_unacc}),0.250000,0.700231,0.208333,0.833333,1.190083,1.0,0.033275,1.798611,0.212963,0.280811,0.444015,0.565427
4,frozenset({doors_2}),frozenset({class_unacc}),0.250000,0.700231,0.188657,0.754630,1.077686,1.0,0.013600,1.221698,0.096115,0.247720,0.181467,0.512026
5,frozenset({persons_2}),frozenset({class_unacc}),0.333333,0.700231,0.333333,1.000000,1.428099,1.0,0.099923,inf,0.449653,0.476033,1.000000,0.738017
6,frozenset({lug_boot_small}),frozenset({class_unacc}),0.333333,0.700231,0.260417,0.781250,1.115702,1.0,0.027006,1.370370,0.155556,0.336826,0.270270,0.576575
7,frozenset({safety_low}),frozenset({class_unacc}),0.333333,0.700231,0.333333,1.000000,1.428099,1.0,0.099923,inf,0.449653,0.476033,1.000000,0.738017
8,"frozenset({lug_boot_big, persons_2})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
9,"frozenset({persons_2, lug_boot_med})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
10,"frozenset({lug_boot_small, persons_2})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
11,"frozenset({persons_2, safety_high})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
12,"frozenset({persons_2, safety_low})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
13,"frozenset({persons_2, safety_med})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
14,"frozenset({safety_low, persons_4})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
15,"frozenset({safety_low, persons_more})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
16,"frozenset({lug_boot_big, safety_low})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
17,"frozenset({safety_low, lug_boot_med})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
18,"frozenset({lug_boot_small, safety_low})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339

In [128]:
rules = rules[rules['consequents'].apply(lambda x: any('class_' in item for item in x))]
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({buying_high}),frozenset({class_unacc}),0.250000,0.700231,0.187500,0.750000,1.071074,1.0,0.012442,1.199074,0.088477,0.245827,0.166023,0.508884
1,frozenset({buying_vhigh}),frozenset({class_unacc}),0.250000,0.700231,0.208333,0.833333,1.190083,1.0,0.033275,1.798611,0.212963,0.280811,0.444015,0.565427
2,frozenset({maint_high}),frozenset({class_unacc}),0.250000,0.700231,0.181713,0.726852,1.038017,1.0,0.006655,1.097458,0.048832,0.236446,0.088803,0.493178
3,frozenset({maint_vhigh}),frozenset({class_unacc}),0.250000,0.700231,0.208333,0.833333,1.190083,1.0,0.033275,1.798611,0.212963,0.280811,0.444015,0.565427
4,frozenset({doors_2}),frozenset({class_unacc}),0.250000,0.700231,0.188657,0.754630,1.077686,1.0,0.013600,1.221698,0.096115,0.247720,0.181467,0.512026
5,frozenset({persons_2}),frozenset({class_unacc}),0.333333,0.700231,0.333333,1.000000,1.428099,1.0,0.099923,inf,0.449653,0.476033,1.000000,0.738017
6,frozenset({lug_boot_small}),frozenset({class_unacc}),0.333333,0.700231,0.260417,0.781250,1.115702,1.0,0.027006,1.370370,0.155556,0.336826,0.270270,0.576575
7,frozenset({safety_low}),frozenset({class_unacc}),0.333333,0.700231,0.333333,1.000000,1.428099,1.0,0.099923,inf,0.449653,0.476033,1.000000,0.738017
8,"frozenset({lug_boot_big, persons_2})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
9,"frozenset({persons_2, lug_boot_med})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
10,"frozenset({lug_boot_small, persons_2})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
11,"frozenset({persons_2, safety_high})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
12,"frozenset({persons_2, safety_low})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
13,"frozenset({persons_2, safety_med})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
14,"frozenset({safety_low, persons_4})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
15,"frozenset({safety_low, persons_more})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
16,"frozenset({lug_boot_big, safety_low})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
17,"frozenset({safety_low, lug_boot_med})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339
18,"frozenset({lug_boot_small, safety_low})",frozenset({class_unacc}),0.111111,0.700231,0.111111,1.000000,1.428099,1.0,0.033308,inf,0.337240,0.158678,1.000000,0.579339

In [117]:
def predict(instance, rules):
    for _, rule in rules.iterrows():
        antecedents = list(rule['antecedents'])
        
        if all(instance[item] == 1 for item in antecedents):
            for c in rule['consequents']:
                if "class_" in c:
                    return c
    return "default_class"